[workspace]

resolver = "2"

members = [
    "daily-contest-67",
    "daily-contest-72",
    "daily-contest-73",
    "daily-contest-74",
    "daily-contest-78",
    "daily-contest-79",
    "daily-contest-82",
    "daily-contest-84",
    "daily-contest-85",
    "daily-contest-88",
    "daily-contest-89",
    "mayocorn-20230915",
    "trooooche_20231024",
]
